gbook/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(

    '',

    url(r'^library/$', 'gbook.views.library', name='library'),
    url(r'^book/(.*)/$', 'gbook.views.book', name='book'),
    url(r'^createbook/$', 'gbook.views.create_book', name='createbook'),
    url(r'^addnote/(.*)/$', 'gbook.views.add_note', name='addnote'),
    url(r'^premoderate/$', 'gbook.views.premoderate', name='premoderate'),

    url(r'^comments/', include('django_comments.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/guestbook/login/'}, name='logout'),
)

guest_book/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^guestbook/', include('gbook.urls')),
    url(r'^admin/', include(admin.site.urls)),
]

gbook/models.py
from django.db import models
from django.conf import settings
from datetime import datetime


MODERATION_STATUS = (
    ('good', 'good'),
    ('bad', 'bad'),
    ('unknown', 'unknown'),
)


class Book(models.Model):
    name = models.CharField(max_length=200)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL)
    slug = models.SlugField(unique=True)
    premoderation = models.BooleanField(default=False)
    date = models.DateTimeField(default=datetime.now)
    def __str__(self):
        return self.name
    class Meta:
        order_with_respect_to = 'owner'
        ordering = ['date', 'name']


class Note(models.Model):
    name = models.CharField(max_length=200, blank=True)
    text = models.TextField()
    checked = models.CharField(max_length=8,
                               choices=MODERATION_STATUS,
                               default='unknown')
    writer = models.ForeignKey(settings.AUTH_USER_MODEL)
    book = models.ForeignKey(Book)
    date = models.DateTimeField(default=datetime.now)
    def __str__(self):
        return self.name
    class Meta:
        order_with_respect_to = 'book'
        ordering = ['date']

gbook/forms.py
from gbook.models import Book, Note
from django.forms import ModelForm


class BookForm(ModelForm):
    " Create book "
    class Meta:
        model = Book
        exclude = ('owner', 'date')


class NoteForm(ModelForm):
    " Add note "
    class Meta:
        model = Note
        exclude = ('checked', 'writer', 'date', 'book')

gbook/views.py
from datetime import datetime

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required

from .models import Book, Note
from .forms import BookForm, NoteForm


@login_required
def library(request):
    """ list of books
    """
    return render(request, 'library.html', {
        'all_books': Book.objects.all(),
    })


@login_required
def book(request, slug):
    """ display all notes and comments
    for selected book (slug)
    """
    return render(request, 'book.html', {
        'book': Book.objects.get(slug=slug),
    })


@login_required
def create_book(request):
    """ create new book
    """
    bookform = BookForm()
    if request.method == 'POST':
        form = BookForm(request.POST)
        if form.is_valid():
            new_book = Book(
                slug=form.cleaned_data['slug'],
                name=form.cleaned_data['name'],
                premoderation=form.cleaned_data['premoderation'],
                owner=request.user,
                date=datetime.now()
            )
            new_book.save()
            return redirect('/guestbook/library/')
    return render(request, 'create_book.html', {'BookForm': bookform})


@login_required
def add_note(request, slug):
    """ add note for selected book (slug)
    """
    noteform = NoteForm()
    book_obj = Book.objects.get(slug=slug)
    if request.method == 'POST':
        form = NoteForm(request.POST)
        if form.is_valid():
            new_note = Note(
                name=form.cleaned_data['name'],
                text=form.cleaned_data['text'],
                book=book_obj,
                checked='good' if book.premoderation == False else 'unknown',
                writer=request.user,
                date=datetime.now()
            )
            new_note.save()
            return redirect('/guestbook/book/%s' % slug)
    return render(request, 'add_note.html',
                  {'NoteForm': noteform, 'slug': slug, 'book': book})


@login_required
def premoderate(request):
    """ premoderate all notes in books of request.user, if book.premoderate == True
    """
    notes = Note.objects.filter(book__owner=request.user,
                                book__premoderation=True,
                                checked='unknown',
                               ).all()
    if request.method == 'POST':
        if request.POST['note_id'] and request.POST['checked'] != 'unknown':
            Note.objects.filter(id=request.POST['note_id'])\
                        .update(checked=request.POST['checked'])
    return render(request, 'premoderate.html', {'notes': notes,})

gbook/templates/add_comment.html
{% extends "base.html" %}

{% block content %}
  <form method="post" action="">
    {% csrf_token %}
    <table>
      {{CommentForm}}
    </table>
    <input type="submit" value="Submit Form"/>
  </form>
{% endblock %}

gbook/templates/add_note.html
{% extends "base.html" %}

{% block content %}
<br>
<h2 class="blog-post-title">Add new note to {{slug}}:</h2>
<br>
  <form method="post" action="">
    {% csrf_token %}
    <table>
      {{NoteForm}}
    </table>
    <input type="submit" value="Add"/>
  </form>
{% endblock %}

gbook/templates/base.html
{% load i18n %}{% load staticfiles %}{% get_current_language as LANGUAGE_CODE %}<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">

  <head>
    <meta charset="utf-8">
    <title>GuestBook</title>
    <link rel="icon" type="image/png" href="{% static "blue64x64.png" %}" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
    <link rel="stylesheet" href="{% static "blog.css" %}">
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    {% block extra_css %}
    {% endblock %}
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="{% static 'html5shiv.js' %}"></script>
      <script src="{% static 'respond.min.js' %}"></script>
    <![endif]-->

  </head>

  <body>

    {% block container %}

    <div class="blog-masthead">
        <div class="container">
         <nav class="blog-nav">
           <a class="blog-nav-item active" href="{% url "library" %}">{% trans "Guest books" %}</a>
           <a class="blog-nav-item" href="{% url "createbook" %}">{% trans "Create guest book" %}</a>
           <a class="blog-nav-item" href="/guestbook/premoderate/">{% trans "Premoderate notes" %}</a>
           <a class="blog-nav-item" href="/guestbook/admin/">{% trans "For admins" %}</a>
            {% if user.is_authenticated %}
            <a class="blog-nav-item" href="{% url "logout" %}">{% trans "Log out" %}</a>
            {% else %}
            <a class="blog-nav-item" href="{% url "login" %}">{% trans "Log in" %}</a>
            {% endif %}
          </nav>
         </div>
    </div>

    <div class="container">

      {% block content_wrapper %}
      {% block content %}
      {% endblock %}
      {% endblock %}

    </div>

    {% endblock %}

    <script src="{% static "jquery.min.js" %}"></script>
    <script src="{% static "bootstrap.min.js" %}"></script>

    {% block extra_js %}
    {% endblock %}

  </body>

</html>

gbook/templates/book.html
{% extends "base.html" %}

{% block content %}
  {% load comments %}

    <div class="container">

      <div class="blog-header">
        <h1 class="blog-title"> {{book.name}} </h1>
      </div>
      <a href="/guestbook/addnote/{{book.slug}}/" class="btn btn-default">add note</a>
      <div class="row">
        <div class="col-sm-8 blog-main">
         {% for note in book.note_set.all %}
          {% if note.checked == 'good' %}
          <div class="blog-post">
            <h2 class="blog-post-title"> {{note.name}} </h2>
            <p class="blog-post-meta"> {{note.date}} </p>
               {{note.text}}
          <p>_</p>
          <font size="3">{% render_comment_list for note %}</font>
          <a href="#{{note.id}}" class="btn btn-default" data-toggle="collapse">add comment</a>
          <div id="{{note.id}}" class="collapse">
                  {% get_comment_form for note as form %}
                  <table>
                    <form action="{% comment_form_target %}" method="post">
                      {% csrf_token %}
                      {{ form }}
                      <tr>
                        <td colspan="2">
                          <input type="submit" name="submit" value="Post">
                          <input type="submit" name="preview" value="Preview">
                        </td>
                      </tr>
                    </form>
                  </table>
          </div>
          </div><!-- /.blog-post -->
         {% endif %}
         {% endfor %}

        </div><!-- /.blog-main -->


      </div><!-- /.row -->

    </div><!-- /.container -->

    <footer class="blog-footer">
      <p>
        <a href="#">Back to top</a>
      </p>
    </footer>



{% endblock %}

gbook/templates/create_book.html
{% extends "base.html" %}
{% block content %}
<br>
<h2 class="blog-post-title">Create new guest book:</h2>
 <br><br>
 <div class="container">
 <div class="col-sm-8 blog-main">
  <form method="post" action="">
    {% csrf_token %}
    <table>
      {{BookForm}}
    </table>
    <br>
    <input type="submit" value="Create"/>
  </form>
 </div>
 </div>
{% endblock %}

gbook/templates/library.html
{% extends "base.html" %}

{% block content %}
     <div class="blog-header">
       <h1 class="blog-title"> All guest books: </h1>
     </div>
     <br>
     <div class="container">
       <div class="row">
         <div class="col-sm-8 blog-main">
          {% for book in all_books %}
             <h2 class="blog-post-title"> <a href="/guestbook/book/{{book.slug}}" >{{book.name}}</a> </h2>
             <p class="blog-post-meta"> {{book.date}} </p>
          {% endfor %}
         </div>
       </div>
     </div>
{% endblock %}